starters/cifar10-baseline/baseline.py
=> Update TPU setup

.azure-pipelines/ipynb-publish.yml, .azure-pipelines/ipynb-tests.yml, .github/workflows/ci_docs.yml, .github/workflows/ci_testing.yml, .github/workflows/pub_notebooks.yml
=> typo in ci_testing.yml

.actions/helpers.py, starters/basic-gan/.meta.yaml
=> fix Colab link & image size

.actions/helpers.py, lightning_examples/basic-gan/gan.py, lightning_examples/cifar10-baseline/baseline.py, lightning_examples/datamodules/datamodules.py, lightning_examples/mnist-hello-world/hello-world.py
=> add setup in notebooks

.actions/helpers.py, .actions/ipynb-render.sh, .actions/ipynb-test.sh, .azure-pipelines/ipynb-publish.yml, .azure-pipelines/ipynb-tests.yml, .github/workflows/ci_testing.yml, course_UvA-DL/graph-neural-networks/.meta.yml, requirements/default.txt
Fixes #38
Not sure how it would work...
=> fix changed & data cache & update Azure triggers

.actions/helpers.py, .github/workflows/docs-deploy.yml
=> extend notebook header

.actions/helpers.py, .azure-pipelines/ipynb-tests.yml, course_UvA-DL/graph-neural-networks/GNN_overview.py, lightning_examples/augmentation_kornia/augmentation.py, lightning_examples/basic-gan/gan.py, lightning_examples/cifar10-baseline/baseline.py, lightning_examples/datamodules/datamodules.py, lightning_examples/mnist-hello-world/hello-world.py, lightning_examples/reinforce-learning-DQN/dqn.py, lightning_examples/text-transformers/text-transformers.py, setup.cfg
=> clean-up ipynb

lightning_examples/mnist-tpu-training/.meta.yml, lightning_examples/mnist-tpu-training/mnist-tpu.py
=> add TPU MNIST

lightning_examples/cifar10-baseline/baseline.py
Edit a line to ``self(x)`` for readability.
We've discussed this on slack.
=> Edit a line to ``self(x)`` for readability

.actions/helpers.py, README.md, template/.meta.yml
=> inline image to notebooks

.actions/git-diff-sync.sh, .actions/ipynb-render.sh, .azure-pipelines/ipynb-publish.yml, lightning_examples/mnist-tpu-training/.meta.yml, sample-template/.meta.yml
=> copy unsupported accel

.azure-pipelines/ipynb-publish.yml, .github/workflows/ci_schema.yml, sample-template/.meta.yml
```
error: pathspec 'Autoencoders (#56)
* Adding GNN tutorial?
?
* Removing starters folder?
?
* Adding Deep Autoencoder Tutorial?
?' did not match any file(s) known to git.
```
=> CD: Fix log commit msg

.actions/ipynb-render.sh, course_UvA-DL/autoregressive-image-modeling/.meta.yml, course_UvA-DL/deep-autoencoders/.meta.yml, course_UvA-DL/deep-energy-based-generative-models/.meta.yml, course_UvA-DL/graph-neural-networks/.meta.yml, course_UvA-DL/normalizing-flows/.meta.yml, course_UvA-DL/transformers-and-MH-attention/.meta.yml, lightning_examples/augmentation_kornia/.meta.yml, lightning_examples/basic-gan/.meta.yaml, lightning_examples/cifar10-baseline/.meta.yml, lightning_examples/datamodules/.meta.yml, lightning_examples/mnist-hello-world/.meta.yml, lightning_examples/mnist-tpu-training/.meta.yml, lightning_examples/reinforce-learning-DQN/.meta.yml, lightning_examples/text-transformers/.meta.yml, lightning_examples/text-transformers/text-transformers.py, sample-template/.meta.yml
=> Fix bug in ipynb-render.sh

course_UvA-DL/activation-functions/Activation_Functions.py
Fixes a small reference that was incorrect!
=> Fix reference

.actions/ipynb-render.sh, .github/workflows/ci_docs.yml, lightning_examples/augmentation_kornia/.meta.yml, lightning_examples/basic-gan/.meta.yaml
=> Fix bad substitution

course_UvA-DL/graph-neural-networks/.meta.yml
=> Pin pytorch geometric version for compatibility with pretrained weights

course_UvA-DL/activation-functions/Activation_Functions.py, course_UvA-DL/autoregressive-image-modeling/Autoregressive_Image_Modeling.py, course_UvA-DL/deep-autoencoders/Deep_Autoencoders.py, course_UvA-DL/deep-energy-based-generative-models/Deep_Energy_Models.py, course_UvA-DL/graph-neural-networks/GNN_overview.py, course_UvA-DL/inception-resnet-densenet/Inception_ResNet_DenseNet.py, course_UvA-DL/initialization-and-optimization/Initialization_and_Optimization.py, course_UvA-DL/introduction-to-pytorch/Introduction_to_PyTorch.py, course_UvA-DL/normalizing-flows/NF_image_modeling.py, course_UvA-DL/transformers-and-MH-attention/Transformers_MHAttention.py
Adds youtube videos of the UvA DL course to the respective notebooks. Similar to #90, but using iframes instead of badges.
=> Adding Youtube videos of UvA DL course as iFrames

course_UvA-DL/01-introduction-to-pytorch/Introduction_to_PyTorch.py
Fixes a few minor typos and bug in Tutorial 2 of the UvA Deep Learning course.
=> UvA DL - Tutorial 2 (Typo corrections)

lightning_examples/mnist-hello-world/hello-world.py
Fixes #107 
Fixes https://github.com/PyTorchLightning/pytorch-lightning/issues/10384
=> Use torchmetrics in MNIST Hello World example

.actions/helpers.py, .actions/ipynb-render.sh, flash_tutorials/electricity_forecasting/.meta.yml
=> Fix requirements containing extras

.actions/helpers.py
Exposes a `patterns` argument in copy notebooks. Useful for just copying over the notebooks you want (e.g. when adding Flash submodule).
=> Expose patterns argument in copy_notebooks

course_UvA-DL/06-graph-neural-networks/.meta.yml
Fixes the issue mentioned in #114. The new PyTorch Geometric broke the checkpoints, which have been accordingly updated. Thus, the PyG version has been updated in the meta file.
=> UvA DLC Tutorial 6: Updated PyG requirement

lightning_examples/text-transformers/.meta.yml, lightning_examples/text-transformers/text-transformers.py
=> Fix mistake in total steps computation for GLUE notebook

.actions/assistant.py, .azure/ipynb-publish.yml, .azure/ipynb-tests.yml, lightning_examples/augmentation_kornia/.meta.yml, lightning_examples/barlow-twins/.meta.yml, lightning_examples/barlow-twins/barlow_twins.py, lightning_examples/basic-gan/.meta.yaml, lightning_examples/cifar10-baseline/.meta.yml, lightning_examples/datamodules/.meta.yml, lightning_examples/mnist-hello-world/.meta.yml, lightning_examples/reinforce-learning-DQN/.meta.yml, lightning_examples/text-transformers/.meta.yml
update the GPUimage from 1.8 to 1.10
=> update the GPU env to PT 1.10

course_UvA-DL/04-inception-resnet-densenet/Inception_ResNet_DenseNet.py, course_UvA-DL/05-transformers-and-MH-attention/Transformers_MHAttention.py, course_UvA-DL/06-graph-neural-networks/.meta.yml, course_UvA-DL/06-graph-neural-networks/GNN_overview.py, course_UvA-DL/08-deep-autoencoders/Deep_Autoencoders.py, course_UvA-DL/09-normalizing-flows/NF_image_modeling.py, course_UvA-DL/10-autoregressive-image-modeling/Autoregressive_Image_Modeling.py, course_UvA-DL/13-contrastive-learning/SimCLR.py
a temporary solution to unblock pending PRs, will be resolved in a systematic way,
similar to https://github.com/PyTorchLightning/pytorch-lightning/pull/12383
=> update API PL v1.6 - Trainer dataloaders

flash_tutorials/electricity_forecasting/electricity_forecasting.py, lightning_examples/augmentation_kornia/augmentation.py, lightning_examples/barlow-twins/barlow_twins.py, lightning_examples/basic-gan/gan.py, lightning_examples/cifar10-baseline/baseline.py, lightning_examples/datamodules/datamodules.py, lightning_examples/mnist-hello-world/hello-world.py, lightning_examples/mnist-tpu-training/mnist-tpu.py, lightning_examples/reinforce-learning-DQN/dqn.py, lightning_examples/text-transformers/text-transformers.py
=> Update PTL examples for v1.6 release

.github/dependabot.yml
- [n/a] Did you make sure to **update the docs**?
- [n/a] Did you write any new **necessary tests**?
See title.
=> CI: Set up dependabot for GitHub Actions

.azure/ipynb-publish.yml, .azure/ipynb-tests.yml
- [n/a] Did you make sure to **update the docs**?
- [n/a] Did you write any new **necessary tests**?
- Part of https://github.com/Lightning-AI/lightning/pull/13831/.
- Updates tags, but nothing changes :)
=> CI: Update docker images

lightning_examples/augmentation_kornia/.meta.yml, lightning_examples/warp-drive/.meta.yml, lightning_examples/warp-drive/multi_agent_rl.py
Fixes the compatibility issue of the notebook (package version and API), as WarpDrive has updated to version 2.
=> compatible with warpdrive v2

.azure/ipynb-publish.yml, .azure/ipynb-tests.yml
- [n/a] Did you make sure to **update the docs**?
- [n/a] Did you write any new **necessary tests**?
Part of https://github.com/Lightning-AI/lightning/pull/15346.
Addresses https://github.com/Lightning-AI/lightning/pull/15345#discussion_r1006455340.
=> Update docker images in CI/CD

.actions/assistant.py, .azure/ipynb-publish.yml
Addresses the publishing branch of #48 and fixes #206
each notebook is running as separate job:
and they commits after sync merge:
see: https://dev.azure.com/Lightning-AI/Tutorials/_build/results?buildId=125521&view=results
=> building notebooks in sequence

_docs/source/conf.py, _requirements/docs.txt
=> Adjust docs requirements

.github/workflows/ci_docs.yml, _docs/source/conf.py, _requirements/docs.txt
flowing the lightning's template freeze due to compatibility issues
=> ci/docs: freeze versions & linkcheck

.actions/assistant.py, .pre-commit-config.yaml, lightning_examples/finetuning-scheduler/finetuning-scheduler.py, lightning_examples/reinforce-learning-DQN/dqn.py, pyproject.toml
=> bump syntax to py3.8 & resolve isort

.azure/ipynb-publish.yml, .azure/ipynb-tests.yml, .codecov.yml, .github/mergify.yml, .github/workflows/ci_block-ipybn.yml, .github/workflows/ci_block-pub.yml, .github/workflows/ci_checks.yml, .github/workflows/ci_docs.yml, .github/workflows/ci_test-acts.yml, .pre-commit-config.yaml, .prettierignore, flash_tutorials/electricity_forecasting/.meta.yml, flash_tutorials/image_classification/.meta.yml, flash_tutorials/tabular_classification/.meta.yml, flash_tutorials/text_classification/.meta.yml, lightning_examples/finetuning-scheduler/.meta.yml, lightning_examples/finetuning-scheduler/RteBoolqModule_ft_schedule_deberta_base.yaml, lightning_examples/warp-drive/.meta.yml
standardize the YAML formatting
=> precommit: enable prettier

.actions/assistant.py, .github/workflows/ci_block-ipybn.yml, .pre-commit-config.yaml, course_UvA-DL/01-introduction-to-pytorch/Introduction_to_PyTorch.py, course_UvA-DL/03-initialization-and-optimization/Initialization_and_Optimization.py, course_UvA-DL/04-inception-resnet-densenet/Inception_ResNet_DenseNet.py, course_UvA-DL/05-transformers-and-MH-attention/Transformers_MHAttention.py, course_UvA-DL/07-deep-energy-based-generative-models/Deep_Energy_Models.py, course_UvA-DL/09-normalizing-flows/NF_image_modeling.py, course_UvA-DL/10-autoregressive-image-modeling/Autoregressive_Image_Modeling.py, course_UvA-DL/11-vision-transformer/Vision_Transformer.py, course_UvA-DL/12-meta-learning/Meta_Learning.py, course_UvA-DL/13-contrastive-learning/SimCLR.py, flash_tutorials/tabular_classification/tabular_classification.py, lightning_examples/augmentation_kornia/augmentation.py, lightning_examples/barlow-twins/barlow_twins.py, lightning_examples/reinforce-learning-DQN/dqn.py, pyproject.toml
=> precommit: enable codespell

.actions/assistant.py, .azure/ipynb-publish.yml, .azure/ipynb-tests.yml, _requirements/docs.txt, lightning_examples/finetuning-scheduler/finetuning-scheduler.py
resolving for https://github.com/Lightning-AI/lightning/pull/17924
=> bump `nbsphinx` & fix labels & resolve sudo

.github/label-change.yml, .github/workflows/labeler-pr.yml, course_UvA-DL/12-meta-learning/.meta.yml, course_UvA-DL/13-contrastive-learning/SimCLR.py, lightning_examples/cifar10-baseline/baseline.py, lightning_examples/datamodules/.meta.yml
some missing dependencies & labeling PRs
=> fix examples & add lebeler

.actions/assistant.py, .actions/requires.txt, .github/workflows/docs-deploy.yml
looking at while copy notebooks:
```
Configuration error:
There is a programmable error in your configuration file:
Traceback (most recent call last):
File "/home/runner/work/tutorials/tutorials/.actions/assistant.py", line 732, in copy_notebooks
path_ipynb_in_dir = AssistantCLI._copy_notebook(
File "/home/runner/work/tutorials/tutorials/.actions/assistant.py", line 775, in _copy_notebook
ipynb = json.load(fopen)
File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/opt/hostedtoolcache/Python/3.9.19/x64/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, …
```
=> ci: debug deploy docs +`simplejson`

.azure/ipynb-publish.yml, .azure/ipynb-validate.yml, .github/workflows/ci_internal.yml, .github/workflows/docs-deploy.yml
=> ci: bump deprecated ubuntu `20.04`
