Lightning-AI/tutorials

.actions/helpers.py, .pre-commit-config.yaml, course_UvA-DL/autoregressive-image-modeling/Autoregressive_Image_Modeling.py, course_UvA-DL/deep-autoencoders/Deep_Autoencoders.py, course_UvA-DL/deep-energy-based-generative-models/Deep_Energy_Models.py, course_UvA-DL/graph-neural-networks/GNN_overview.py, course_UvA-DL/normalizing-flows/NF_image_modeling.py, course_UvA-DL/transformers-and-MH-attention/Transformers_MHAttention.py, lightning_examples/reinforce-learning-DQN/dqn.py
=> CI: pre-commit docformatter

lightning_examples/reinforce-learning-DQN/.meta.yml, lightning_examples/reinforce-learning-DQN/dqn.py
- I raised this issue on github, issue https://github.com/PyTorchLightning/pytorch-lightning/discussions/10883. The user @awaelchli said to fork the repo, clone it to my local machine, make my changes, push to my repo, and then submit a pull request.
- This is my first attempt to contribute to an open-source project, so please let me know if I've done anything incorrectly.
- I could not find where the unit tests are kept for the example colab notebooks. I would be happy to upload my unit tests for the get_epsilon method, but I don't know where to put them in the codebase.
This fixes issue  https://github.com/PyTorchLightning/pytorch-lightning/discussions/10883, where there was an incorrect version of epsilon decay for the epsilon-random policy of a DQN. The original code has a single …
=> Fixed epsilon decay in dqn example

docs/source/index.rst, flash_tutorials/electricity_forecasting/.meta.yml, flash_tutorials/electricity_forecasting/electricity_forecasting.py
=> Fix electricity forecasting tutorial

.actions/assistant.py, .github/CONTRIBUTING.md, .github/workflows/ci_docs.yml, course_UvA-DL/09-normalizing-flows/NF_image_modeling.py, course_UvA-DL/10-autoregressive-image-modeling/Autoregressive_Image_Modeling.py, docs/source/conf.py, lightning_examples/datamodules/.meta.yml, lightning_examples/mnist-tpu-training/.meta.yml, lightning_examples/mnist-tpu-training/mnist-tpu.py
To prevent some random broken links rather use `stable` than `latest`
=> Docs: link stable versions

.actions/assistant.py, .azure/ipynb-publish.yml, requirements/devel.txt
Fixes #136 .
With the latest papermill release (2.3.4, updated 2022.01.22), a [PR has been included](https://github.com/nteract/papermill/pull/608) that necessitates a change in our papermill.cli references to papermill
As part of the `make ipynb` process, you'll notice `python -m papermill.cli {ipynb_file} {pub_ipynb} --kernel python` fails. Updating it to `python -m papermill {ipynb_file} {pub_ipynb} --kernel python` succeeds.
In this PR I'm submitting to fix this, I'm also updating requirements to ensure papermill >=2.3.4 as previously, `papermill.cli` was necessary.
The [improvement to papermill](https://github.com/nteract/papermill/pull/608) was originally made by @Borda and now is finally available. Thanks! …
=> Adjust papermill references for the release of 2.3.4

.actions/assistant.py, .actions/git-diff-sync.sh, .actions/requirements.txt, .actions/test_cli.py, .github/workflows/ci_test-acts.yml, README.md, setup.cfg, templates/titanic/tutorial.py
Add some testing of internal CLI
=> CI: add internal testing

.github/workflows/ci_code-format.yml, .github/workflows/ci_docs.yml, .github/workflows/ci_schema.yml, lightning_examples/mnist-hello-world/hello-world.py, lightning_examples/mnist-tpu-training/.meta.yml
Fix some broken links and set this job to run nightly to early discover something is wrong...
=> CI: docs nightly

.pre-commit-config.yaml, course_UvA-DL/01-introduction-to-pytorch/Introduction_to_PyTorch.py, course_UvA-DL/03-initialization-and-optimization/Initialization_and_Optimization.py, course_UvA-DL/07-deep-energy-based-generative-models/Deep_Energy_Models.py, course_UvA-DL/11-vision-transformer/Vision_Transformer.py
Same as https://github.com/PyTorchLightning/pytorch-lightning/pull/12542
currently failing on master.
=> Bump version of black to 22.3.0

.actions/assistant.py, .azure/ipynb-publish.yml, .azure/ipynb-tests.yml, .github/workflows/ci_docs.yml, .github/workflows/ci_testing.yml, Makefile, templates/simple/.meta.yml
for generating bash script define the output file so eventual errors are not hidden in the generated scripts
=> ci: use script outputs

Makefile
=> update Makefile to reference new assistant.py func name

lightning_examples/basic-gan/gan.py, lightning_examples/datamodules/.meta.yml
(doc improvement)
Fixes # broken link in gan tutorial
=> update broken gan/datamodules tutorial links

lightning_examples/augmentation_kornia/augmentation.py, lightning_examples/basic-gan/.meta.yaml, lightning_examples/basic-gan/gan.py, lightning_examples/cifar10-baseline/.meta.yml, lightning_examples/cifar10-baseline/baseline.py, lightning_examples/mnist-hello-world/.meta.yml, lightning_examples/mnist-hello-world/hello-world.py, lightning_examples/reinforce-learning-DQN/.meta.yml, lightning_examples/reinforce-learning-DQN/dqn.py, templates/img-classify/classify.py
This allows us to inline training charts :rabbit: 
Part of #19
=> replace TensorBoard by CSV logger in PL examples

lightning_examples/text-transformers/text-transformers.py
This proposal fixes two bugs in the Huggingface transformers pytorch lightning example:
1) The example did not work on the stsb task for GLUE, as you have the wrong if condition (it is always true). Changing `>= 1` to `> 1` fixes it.
2) The train data loader did not shuffle the dataset, which leads to quite a large performance drop for some datasets on glue. Adding shuffle=True to the train dataloader fixes it and gives comparable results to e.g. the HuggingFace trainer class.
Also note that this needs to be fixed in the docs:
https://pytorch-lightning.readthedocs.io/en/stable/notebooks/lightning_examples/text-transformers.html
When you click on that page on "Edit on Github", it leads to a 404 page.
=> Bugfix text-transformers.py

lightning_examples/warp-drive/.meta.yml, lightning_examples/warp-drive/multi_agent_rl.py
=> Update WarpDrive notebook with fixes

lightning_examples/warp-drive/.meta.yml, lightning_examples/warp-drive/multi_agent_rl.py
=> Update warpdrive tutorial

.azure/ipynb-publish.yml, .azure/ipynb-tests.yml, .github/workflows/ci_testing.yml, docs/source/conf.py, lightning_examples/finetuning-scheduler/.meta.yml, lightning_examples/finetuning-scheduler/finetuning-scheduler.py
Closes #178
Fixes #174
Explicitly reference `language = "en"` to avoid new warning. 
Note build-docs check will not pass until #176  is merged. CI testing/nbval check won't pass until #178 is merged.
=> sphinx conf warning fix

.azure/ipynb-publish.yml, .azure/ipynb-tests.yml, .github/workflows/ci_docs.yml, .github/workflows/ci_schema.yml
* fix typing for Azure
* disable CI docs on main
Fixes # (issue)
=> CI: update schema

lightning_examples/augmentation_kornia/augmentation.py
- [n/a] Did you make sure to **update the docs**?
- [n/a] Did you write any new **necessary tests**?
Fixes #204.
The warning I'm trying to fix in this PR
```
(notebooks/lightning_examples/augmentation_kornia: line  128) The name of the builder is: linkcheck
Warning, treated as error:
/Users/nitta/work/github.com/Lightning-AI/tutorials/docs/source/notebooks/lightning_examples/augmentation_kornia.ipynb.rst:128:broken link: https://www.kornia.org (HTTPSConnectionPool(host='www.kornia.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)'))))
make: *** [linkcheck] Error 2
```
If we didn't discuss your PR in Github issues there's a high …
=> Rebuild the Kornia example to update the updated link in the old built notebook

.actions/assistant.py, .github/workflows/ci_code-format.yml, flash_tutorials/image_classification/image_classification.py, flash_tutorials/tabular_classification/tabular_classification.py, flash_tutorials/text_classification/text_classification.py, lightning_examples/augmentation_kornia/.meta.yml, lightning_examples/augmentation_kornia/augmentation.py, requirements/devel.txt
**Fix scripts: remove /usr/bin/python**
Fixing the publishing workflow. Sorry, this was overlooked in #183 by me. Wasn't aware that it will go as a cell. Let's see what does the CI do now.
=> Fix scripts and docs

_requirements/devel.txt, lightning_examples/finetuning-scheduler/.meta.yml, lightning_examples/finetuning-scheduler/finetuning-scheduler.py
Three minor updates to the Fine-Tuning Scheduler tutorial to better support the release of Lightning 1.9.x (supported by Fine-Tuning Scheduler 0.4.x)
- updated the list of supported strategies (**Multi-phase Scheduled Fine-Tuning with FSDP** is now supported! Noted deprecation of Fairscale-based strategies like ``ddp_sharded``)
- [See the FSDP tutorial here if interested.](https://finetuning-scheduler.readthedocs.io/en/stable/advanced/fsdp_scheduled_fine_tuning.html)
- Added references to [``StrategyAdapter``](https://finetuning-scheduler.readthedocs.io/en/stable/api/finetuning_scheduler.strategy_adapters.html#finetuning_scheduler.strategy_adapters.StrategyAdapter)s. If users want to extend Fine-Tuning Scheduler (FTS) to use a custom, currently unsupported strategy or override current FTS …
=> Minor Fine-Tuning Scheduler Tutorial Updates for Lightning 1.9.x

.github/workflows/ci_checks.yml, .pre-commit-config.yaml, _requirements/default.txt, course_UvA-DL/01-introduction-to-pytorch/.meta.yml, course_UvA-DL/01-introduction-to-pytorch/Introduction_to_PyTorch.py, course_UvA-DL/02-activation-functions/.meta.yml, course_UvA-DL/02-activation-functions/Activation_Functions.py, course_UvA-DL/03-initialization-and-optimization/.meta.yml, course_UvA-DL/03-initialization-and-optimization/Initialization_and_Optimization.py, course_UvA-DL/04-inception-resnet-densenet/.meta.yaml, course_UvA-DL/04-inception-resnet-densenet/Inception_ResNet_DenseNet.py, course_UvA-DL/05-transformers-and-MH-attention/.meta.yml, course_UvA-DL/05-transformers-and-MH-attention/Transformers_MHAttention.py, course_UvA-DL/06-graph-neural-networks/.meta.yml, course_UvA-DL/06-graph-neural-networks/GNN_overview.py, course_UvA-DL/07-deep-energy-based-generative-models/.meta.yml, course_UvA-DL/07-deep-energy-based-generative-models/Deep_Energy_Models.py, course_UvA-DL/08-deep-autoencoders/.meta.yml, course_UvA-DL/08-deep-autoencoders/Deep_Autoencoders.py, course_UvA-DL/09-normalizing-flows/.meta.yml, course_UvA-DL/09-normalizing-flows/NF_image_modeling.py, course_UvA-DL/10-autoregressive-image-modeling/.meta.yml, course_UvA-DL/10-autoregressive-image-modeling/Autoregressive_Image_Modeling.py, course_UvA-DL/11-vision-transformer/.meta.yml, course_UvA-DL/11-vision-transformer/Vision_Transformer.py, course_UvA-DL/12-meta-learning/.meta.yml, course_UvA-DL/12-meta-learning/Meta_Learning.py, course_UvA-DL/13-contrastive-learning/.meta.yml, course_UvA-DL/13-contrastive-learning/SimCLR.py
Updates all notebooks to support Lightning 2.0.
This PR depends on #222 
=> Update course tutorials to Lightning 2.0

lightning_examples/finetuning-scheduler/.meta.yml, lightning_examples/finetuning-scheduler/finetuning-scheduler.py
A few minor updates to the Fine-Tuning Scheduler Tutorial to simplify it slightly and better accommodate the Lightning and PyTorch 2.0.x releases. 
1. Support for PyTorch and PyTorch Lightning 2.0.0! Note that ``lightning>=2.0.0`` is a dependency of ``finetuning-scheduler`` 2.0.0 which this tutorial requires.
2. Use the unified `lightning` package rather than the standalone package. Fine-Tuning Scheduler (FTS) by default depends upon the `lightning` package rather than the standalone `pytorch-lightning` package beginning with FTS 2.0 (though the latter can still be installed and used similar to Lightning).
3. Leverage a feature now available in ``finetuning-scheduler`` 2.0.0 to simplify the example.
4. Updated the list of distributed strategies FTS supports as of FTS 2.x.
5. Further …
=> Fine-Tuning Scheduler Tutorial Updates for Lightning 2.0.x

_requirements/default.txt, lightning_examples/finetuning-scheduler/.meta.yml, lightning_examples/finetuning-scheduler/finetuning-scheduler.py
A single update to the Fine-Tuning Scheduler Tutorial to indicate that optimizer reinitialization is now supported! :tada: :rocket:  
A link to the relevant [advanced tutorial](https://finetuning-scheduler.readthedocs.io/en/stable/advanced/optimizer_reinitialization.html) in the official FTS documentation is included. Hoping this might also perhaps re-trigger an update to get the ``2.0.x`` version of the tutorial published. 
(as an aside, the more permissive ``matplotlib`` version dependency that is ready to be merged in [#247](https://github.com/Lightning-AI/tutorials/pull/247) is included in this PR because I saw the older version started having installation issues)
Thanks again to Lightning team for your continuously impressive work!
@Borda @awaelchli 
Anyone in the community is free …
=> Fine-Tuning Scheduler Tutorial Update

.azure/ipynb-publish.yml, .github/workflows/ci_docs.yml, templates/simple/.meta.yml
turned out that last lines were skipped, see https://stackoverflow.com/a/12919766
=> fix bash loading last line from file

.github/workflows/ci_docs.yml, .github/workflows/ci_schema.yml, .github/workflows/ci_test-acts.yml, course_UvA-DL/07-deep-energy-based-generative-models/Deep_Energy_Models.py
=> ci/docs: split building html | linkcheck

.actions/assistant.py, .github/workflows/docker-build.yml, _dockers/README.md, _dockers/ubuntu-cuda/Dockerfile
=> ci: building custom base image

.actions/assistant.py, _docs/source/conf.py
Seems we have some problems with course 13:
```
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/sphinx/config.py", line 350, in eval_config_file
exec(code, namespace)
File "/home/runner/work/lightning/lightning/docs/source-pytorch/conf.py", line 68, in <module>
assist_nb.AssistantCLI.copy_notebooks(
File "/home/runner/work/lightning/lightning/docs/source-pytorch/../../_notebooks/.actions/assistant.py", line 648, in copy_notebooks
ipynb = json.load(f)
File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/json/__init__.py", line 293, in load
return loads(fp.read(),
File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File …
```
=> cli: allow skip notebooks from being copied

.actions/assistant.py
try to make a notebook copy and if fail warn about the error and not crash...
this helps in multiple directions:
- allow skip failing notebooks so as not to block docs build
- add notebook name so we can track back with multi-job build
- still can enforce full docs build with treating warnings as error
=> assitent: try copy notebok else warn

.actions/git-diff-sync.sh, .actions/requires.txt, .azure/ipynb-validate.yml, .github/workflows/ci_internal.yml
fixing internal tests and some other notebooks
```
Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [48 lines of output]
running egg_info
writing lib3/PyYAML.egg-info/PKG-INFO
writing dependency_links to lib3/PyYAML.egg-info/dependency_links.txt
writing top-level names to lib3/PyYAML.egg-info/top_level.txt
Traceback (most recent call last):
File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
main()
File "/opt/hostedtoolcache/Python/3.10.14/x64/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File …
```
=> ci: dont crash if testing matrix is empty

.actions/assistant.py, .actions/test_cli.py, .azure/ipynb-validate.yml, course_UvA-DL/requirements.txt
let's update all notebooks if any requirement in the "book"/default has changed 
=> ci: trigger on parent update

.actions/requires.txt, course_UvA-DL/requirements.txt
Addressing https://github.com/Lightning-AI/pytorch-lightning/pull/20111
```
The conflict is caused by:
The user requested PyYAML<5.4
lightning 2.4.0.dev0 depends on PyYAML<6.1.0 and >=5.4
```
=> req: lift `pyYAML` version freeze

lightning_examples/finetuning-scheduler/finetuning-scheduler.py, lightning_examples/finetuning-scheduler/requirements.txt
Validated (locally) the Fine-Tuning Scheduler (FTS) tutorial for FTS/Lightning/PyTorch `2.4.0` (as of the [recent `2.4.0` Lightning commit](https://github.com/Lightning-AI/lightning/tree/2064887b12dd934a5f9a2bf45897f29e3bfc74d1)). 
(this PR is currently using `2.3.3` until Lightning and FTS `2.4.x` are released)
The only minor changes in this PR are to explicitly set `datasets` `trust_remote_code` (which will be mandatory with Datasets 3.x) and to remove a reference to the now unsupported PT `2.0.x`
Thank you for all your work and your consistently valuable contributions to the open-source ML community!
Updates the Fine-Tuning Scheduler tutorial to prepare for `2.4.0` tutorial publishing.
If we didn't discuss …
=> Fine-Tuning Scheduler Tutorial Update for Lightning/PyTorch `2.4.0`

lightning_examples/basic-gan/gan.py
Fixes https://github.com/Lightning-AI/tutorials/issues/306
I had ! Glad to contribute to the best Pytorch wrapper 🙃
- The quality of the generated samples remains low, but I don't have the time to tune the architecture more. Also, applying tricks to reach Nash equilibrium like label smoothing could make the example less understandable, so I left it as it is.
- This PR was motivated in the case of some heavy generator and discriminator that we don't want to call multiple times. I removed the repeated calls to the generator (which changes the optimization problem a bit, because the discriminator is trained to detect the same …
=> Refactor basic GAN tutorial

lightning_examples/barlow-twins/barlow_twins.py
Validation dataset uses train transforms instead of validation transforms.
=> Fixing used `val_transform` in barlow_twins.py

lightning_examples/finetuning-scheduler/finetuning-scheduler.py, lightning_examples/finetuning-scheduler/requirements.txt
- Validated (locally) the Fine-Tuning Scheduler (FTS) tutorial for FTS/Lightning/PyTorch ``2.5.0``.
- Prepared for HF ``clean_up_tokenization_spaces`` behavior change, 
- Added reference to FTS enhanced support for ``ModelParallelStrategy`` enabling use of PyTorch composable distributed (e.g. ``fully_shard``, ``checkpoint``) and Tensor Parallelism (TP) APIs
Thank you for all your work and your consistently valuable contributions to the open-source ML community!
Updates the Fine-Tuning Scheduler tutorial to prepare for `2.5.0` tutorial publishing.
=> Fine-Tuning Scheduler Tutorial Update for Lightning/PyTorch ``2.5.0``

course_UvA-DL/06-graph-neural-networks/requirements.txt, lightning_examples/reinforce-learning-DQN/requirements.txt, lightning_examples/text-transformers/requirements.txt
Found while checking failed bumps that the issue are unrelated to the particular bumps
=> pin requirements for broken notebooks
